services:
  db:
    image: mongo
    restart: always
    container_name: godo-db
    ports:
      - 27017:27017
    env_file:
      - ./.env.local
    volumes:
      - godo-data:/data/db

  db-test:
    image: mongo
    restart: always
    container_name: godo-test-db
    ports:
      - 27018:27017
    env_file:
      - ./.env.test.local

 
  admin:
    image: mongo-express
    restart: always
    container_name: godo-admin
    ports:
      - 8081:8081
    env_file:
      - ./.env.local

volumes:
  godo-data:
